# Generated by Django 5.2.3 on 2025-06-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_account_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.CharField(choices=[('student', 'student'), ('Teacher', 'Teacher'), ('Parent', 'Parent'), ('guest', 'guest')], max_length=20),
        ),
    ]
