# Generated by Django 5.2.4 on 2025-07-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_categories_language_level_levels_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
